Add ECMAScript module support
mathiasbynens/emoji-regex pull request #99
Opened 2022-03-10 04:04 UTC by nstringham

This PR solves the same problem as #37 but in a different way

this PR also fixes #89

this PR allows users to do
```js
import emojiRegex from 'emoji-regex';
```
or
```js
const { default: emojiRegex } = await import('emoji-regex');
```
or
```js
const emojiRegex = require('emoji-regex');
```

it does this by adding index.mjs which is like index.js except that is an es module instead of a commonjs module

2022-09-29 09:40 UTC, chihabeeddine commented
is there a reason why this pull request still open ?

2022-09-29 14:02 UTC, mathiasbynens requested changes

2022-09-29 14:02 UTC, mathiasbynens commented on script/build.js
> +fs.writeFileSync("./index.mjs", outputModule);
To match the surrounding code style:

```suggestion
fs.writeFileSync('./index.mjs', outputModule);
```

2022-09-29 14:02 UTC, mathiasbynens commented on src/index.mjs
> +export default () =>{
```suggestion
export default () => {
```

2022-09-29 14:02 UTC, mathiasbynens commented on test/tests.js
> +	it('can be imported as an ecmascript module', async () => {
```suggestion
	it('can be imported as a JavaScript module', async () => {
```

2022-09-29 14:02 UTC, mathiasbynens commented on index.mjs
> +export default () =>{
```suggestion
export default () => {
```

2022-09-29 14:02 UTC, mathiasbynens approved these changes

2022-09-29 14:03 UTC, merged

2022-09-29 14:03 UTC, mathiasbynens commented
Thanks!

2025-02-12 10:27 UTC, himanshugogroup commented
Still getting error->>> `TypeError: (0 , emoji_regex_1.default) is not a function`
For
```
    import  emojiRegex from 'emoji-regex';
    const emgRegex = emojiRegex(); <-- Failing here
```

2025-03-03 20:53 UTC, nstringham commented
@himanshugogroup can you share a code example to reproduce your error? It's likely that this error is caused by a misconfigured build system. Are you using Typescript?